SET client_encoding = 'UTF8';

-- Insert a candidate. The password is seeded in plain text ('test123'); on first
-- backend startup PasswordHashMigration re-hashes any plaintext password to bcrypt.
INSERT INTO candidates (username, email, password_hash, name)
VALUES ('candidate1', 'candidate1@example.com', 'test123', 'John Doe');

-- ── Section 1: pattern MCQs (section defaults to 'pattern') ──
INSERT INTO questions (question_text, question_type, pattern_data, options, correct_option_index)
VALUES
('What comes next in the sequence?',
 'number_sequence', '{"sequence": [2, 4, 8, 16, "?"]}', '["24", "28", "32", "36"]', 2),
('Identify the missing number.',
 'number_sequence', '{"sequence": [3, 6, 11, 18, "?"]}', '["25", "27", "29", "31"]', 1),
('What is the next number?',
 'number_sequence', '{"sequence": [100, 50, 25, "?"]}', '["10", "12", "12.5", "15"]', 2),
('Which number continues the pattern?',
 'number_sequence', '{"sequence": [5, 10, 20, 40, "?"]}', '["60", "70", "75", "80"]', 3),
('Find the pattern and choose the missing value.',
 'number_sequence', '{"sequence": [1, 1, 2, 3, 5, 8, "?"]}', '["11", "12", "13", "14"]', 2),
('Spot the rule and find the next term.',
 'number_sequence', '{"sequence": [144, 121, 100, 81, "?"]}', '["64", "72", "68", "60"]', 0),
('What value replaces the question mark?',
 'number_sequence', '{"sequence": [7, 14, 28, 56, "?"]}', '["96", "108", "112", "120"]', 2),
('Find the next number in the series.',
 'number_sequence', '{"sequence": [1, 4, 9, 16, 25, "?"]}', '["30", "36", "42", "49"]', 1),
('What comes next?',
 'number_sequence', '{"sequence": [0, 1, 3, 6, 10, "?"]}', '["13", "14", "15", "16"]', 2),
('Identify the next value.',
 'number_sequence', '{"sequence": [2, 6, 18, 54, "?"]}', '["108", "148", "162", "172"]', 2),
('How many shapes come next?',
 'shape_pattern',
 '{"sequence": [{"shape": "▲", "count": 1}, {"shape": "▲", "count": 2}, {"shape": "▲", "count": 4}, {"shape": "?", "count": 0}]}',
 '["6", "7", "8", "9"]', 2),
('How many shapes come next in the sequence?',
 'shape_pattern',
 '{"sequence": [{"shape": "●", "count": 1}, {"shape": "●", "count": 3}, {"shape": "●", "count": 6}, {"shape": "?", "count": 0}]}',
 '["8", "9", "10", "12"]', 2),
('What is the next count in this shape pattern?',
 'shape_pattern',
 '{"sequence": [{"shape": "■", "count": 2}, {"shape": "■", "count": 4}, {"shape": "■", "count": 6}, {"shape": "?", "count": 0}]}',
 '["7", "8", "9", "10"]', 1),
('Complete the shape sequence.',
 'shape_pattern',
 '{"sequence": [{"shape": "★", "count": 1}, {"shape": "★", "count": 4}, {"shape": "★", "count": 9}, {"shape": "?", "count": 0}]}',
 '["12", "14", "16", "18"]', 2),
('Complete the matrix pattern.',
 'matrix', '{"grid": [[1, 2, 3], [4, 5, 6], [7, 8, "?"]]}', '["7", "8", "9", "10"]', 2),
('Find the missing value in the matrix.',
 'matrix', '{"grid": [[2, 4, 8], [3, 9, 27], [4, 16, "?"]]}', '["32", "48", "56", "64"]', 3),
('What completes this matrix?',
 'matrix', '{"grid": [[1, 2, 3], [2, 4, 6], [3, 6, "?"]]}', '["7", "8", "9", "12"]', 2),
('What number is missing?',
 'number_sequence', '{"sequence": [81, 27, 9, 3, "?"]}', '["0", "1", "2", "3"]', 1),
('Find the next term.',
 'number_sequence', '{"sequence": [2, 3, 5, 7, 11, "?"]}', '["12", "13", "14", "15"]', 1),
('What comes next in this pattern?',
 'number_sequence', '{"sequence": [1, 2, 4, 7, 11, "?"]}', '["14", "15", "16", "17"]', 2),
('What comes next in the sequence?',
 'number_sequence', '{"sequence": [5, 10, 15, 20, "?"]}', '["24", "25", "30", "35"]', 1),
('Find the next odd number.',
 'number_sequence', '{"sequence": [1, 3, 5, 7, "?"]}', '["8", "9", "10", "11"]', 1),
('What comes next as the numbers decrease?',
 'number_sequence', '{"sequence": [90, 80, 70, 60, "?"]}', '["40", "45", "50", "55"]', 2),
('Spot the rule and find the missing value.',
 'number_sequence', '{"sequence": [2, 5, 10, 17, "?"]}', '["24", "26", "28", "30"]', 1),
('The gap grows each step — what comes next?',
 'number_sequence', '{"sequence": [3, 4, 6, 9, 13, "?"]}', '["16", "17", "18", "19"]', 2),
('Each gap increases by two — find the next term.',
 'number_sequence', '{"sequence": [3, 6, 11, 18, 27, "?"]}', '["36", "38", "40", "42"]', 1),
('Each term multiplies by a growing factor — what is next?',
 'number_sequence', '{"sequence": [1, 2, 6, 24, "?"]}', '["96", "100", "120", "144"]', 2),
('Continue the Fibonacci sequence.',
 'number_sequence', '{"sequence": [1, 1, 2, 3, 5, 8, 13, "?"]}', '["18", "19", "20", "21"]', 3),
('These are perfect cubes — what comes next?',
 'number_sequence', '{"sequence": [1, 8, 27, 64, "?"]}', '["100", "121", "125", "216"]', 2),
('Identify the rule behind this series and continue it.',
 'number_sequence', '{"sequence": [2, 3, 5, 7, 11, 13, "?"]}', '["14", "15", "16", "17"]', 3),
('How many shapes come next?',
 'shape_pattern',
 '{"sequence": [{"shape": "▲", "count": 1}, {"shape": "▲", "count": 2}, {"shape": "▲", "count": 3}, {"shape": "?", "count": 0}]}',
 '["3", "4", "5", "6"]', 1),
('How many shapes come next in the sequence?',
 'shape_pattern',
 '{"sequence": [{"shape": "●", "count": 5}, {"shape": "●", "count": 10}, {"shape": "●", "count": 15}, {"shape": "?", "count": 0}]}',
 '["18", "20", "25", "30"]', 1),
('The count doubles each step — how many come next?',
 'shape_pattern',
 '{"sequence": [{"shape": "■", "count": 1}, {"shape": "■", "count": 2}, {"shape": "■", "count": 4}, {"shape": "■", "count": 8}, {"shape": "?", "count": 0}]}',
 '["12", "14", "16", "18"]', 2),
('The gap between counts grows by one — how many come next?',
 'shape_pattern',
 '{"sequence": [{"shape": "★", "count": 2}, {"shape": "★", "count": 3}, {"shape": "★", "count": 5}, {"shape": "★", "count": 8}, {"shape": "?", "count": 0}]}',
 '["11", "12", "13", "14"]', 1),
('These are triangular numbers — how many shapes come next?',
 'shape_pattern',
 '{"sequence": [{"shape": "▲", "count": 1}, {"shape": "▲", "count": 3}, {"shape": "▲", "count": 6}, {"shape": "▲", "count": 10}, {"shape": "?", "count": 0}]}',
 '["13", "14", "15", "16"]', 2),
('Complete the matrix pattern.',
 'matrix', '{"grid": [[2, 4, 6], [8, 10, 12], [14, 16, "?"]]}', '["17", "18", "19", "20"]', 1),
('What completes this matrix?',
 'matrix', '{"grid": [[3, 6, 9], [12, 15, 18], [21, 24, "?"]]}', '["25", "26", "27", "28"]', 2),
('Every cell is a perfect square — find the missing value.',
 'matrix', '{"grid": [[1, 4, 9], [16, 25, 36], [49, 64, "?"]]}', '["72", "78", "81", "100"]', 2),
('The third column follows from the first two — what is missing?',
 'matrix', '{"grid": [[2, 3, 5], [4, 6, 10], [6, 9, "?"]]}', '["12", "14", "15", "18"]', 2),
('Two rules combine in this matrix — find the missing value.',
 'matrix', '{"grid": [[2, 3, 4], [4, 9, 16], [6, 27, "?"]]}', '["32", "36", "48", "64"]', 1);

-- ── Section 2: fixed drag-and-drop activities (one per type). ──
-- items/zones are shown to the candidate; answer_key is server-only.
-- created_at increments so findActivities() returns them in a stable order.
INSERT INTO questions (section, question_text, question_type, prompt, items, zones, answer_key, suffix, created_at)
VALUES
('drag', 'Sort each item into its group', 'categorize',
 'Drag each item into the group it belongs to.',
 '[{"id":"apple","label":"Apple"},{"id":"banana","label":"Banana"},{"id":"dog","label":"Dog"},{"id":"cat","label":"Cat"},{"id":"red","label":"Red"},{"id":"blue","label":"Blue"}]',
 '[{"id":"fruit","label":"Fruit"},{"id":"animal","label":"Animal"},{"id":"color","label":"Color"}]',
 '{"apple":"fruit","banana":"fruit","dog":"animal","cat":"animal","red":"color","blue":"color"}',
 NULL, NOW() + INTERVAL '1 second'),

('drag', 'Match each word to its opposite', 'match',
 'Drag each word on the left onto its opposite on the right.',
 '[{"id":"day","label":"Day"},{"id":"hot","label":"Hot"},{"id":"up","label":"Up"},{"id":"big","label":"Big"}]',
 '[{"id":"night","label":"Night"},{"id":"cold","label":"Cold"},{"id":"down","label":"Down"},{"id":"small","label":"Small"}]',
 '{"day":"night","hot":"cold","up":"down","big":"small"}',
 NULL, NOW() + INTERVAL '2 second'),

('drag', 'Put the numbers in order', 'sequence',
 'Arrange the numbers from smallest to largest.',
 '[{"id":"one","label":"One"},{"id":"two","label":"Two"},{"id":"three","label":"Three"},{"id":"four","label":"Four"},{"id":"five","label":"Five"}]',
 '[]',
 '["one","two","three","four","five"]',
 NULL, NOW() + INTERVAL '3 second'),

('drag', 'Rank by size', 'rank',
 'Arrange the animals from largest to smallest.',
 '[{"id":"elephant","label":"Elephant"},{"id":"horse","label":"Horse"},{"id":"dog","label":"Dog"},{"id":"ant","label":"Ant"}]',
 '[]',
 '["elephant","horse","dog","ant"]',
 NULL, NOW() + INTERVAL '4 second'),

('drag', 'Complete the sentence', 'fill-blank',
 'Drag the correct word into each blank. Some words are not used.',
 '[{"id":"cat","label":"cat"},{"id":"mouse","label":"mouse"},{"id":"tree","label":"tree"},{"id":"dog","label":"dog"},{"id":"wall","label":"wall"}]',
 '[{"id":"b1","label":"The "},{"id":"b2","label":" chased the "},{"id":"b3","label":" up the "}]',
 '{"cat":"b1","mouse":"b2","tree":"b3"}',
 '.', NOW() + INTERVAL '5 second');
